version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - '5432:5432'
  backend:
    image: testapp:xmlparser-0.0.1-SNAPSHOT
    pull_policy: never
    healthcheck:
      test: "wget --no-verbose --tries=1 --no-check-certificate --spider http://localhost:8000/actuator/health || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    links:
      - "db:xmlparser"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: xmlparser@testapp.com
      PGADMIN_DEFAULT_PASSWORD: password123
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8008:80'
    links:
      - "db:xmlparser"